select * from Customer_behavior

--Q1. What is the total revenue generated by male vs.female customers?--
select gender,SUM(purchased_amount) as revenue from Customer_behavior group by gender;

--Q2. Which customers used a discount but still  spent more than the average purchase amount?--
select customer_id,purchased_amount from Customer_behavior where discount_applied = 'Yes'and purchased_amount >= (select Avg(purchased_amount) from Customer_behavior);

--Q3. Which are top 5 products with the highest average review rating?--
SELECT TOP 5 
    item_purchased,
    ROUND(AVG(CAST(review_rating AS FLOAT)), 2) AS Average_Product_Ratings
FROM Customer_behavior
GROUP BY item_purchased
ORDER BY AVG(CAST(review_rating AS FLOAT)) DESC;

--Q4. Compare the average Purchased Amount between Standard and Express Shipping.--
SELECT 
    shipping_type,
    ROUND(AVG(purchased_amount), 2) AS avg_purchase_amount
FROM Customer_behavior
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

--Q5.Do subscribed customers spend more? Compare average spend and total revenue between subcribers and non-subcribers--
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchased_amount), 2) AS avg_spend,
    ROUND(SUM(purchased_amount), 2) AS total_revenue

FROM Customer_behavior
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

--Q6.Which 5 products have the highest percentage of purchases with discount applied.--
SELECT TOP 5
    item_purchased,
    ROUND(100 *
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
        / COUNT(*), 
    2) AS discount_rate
FROM Customer_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC;

--Q7.Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and the count of each segment. --
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM Customer_behavior
)

SELECT 
    customer_segment,
    COUNT(DISTINCT customer_id) AS number_of_customers
FROM customer_type
GROUP BY customer_segment
ORDER BY number_of_customers DESC;


--Q8. --What are the top 3 most purchased products within each category?--
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders
    FROM Customer_behavior
    GROUP BY category, item_purchased
),
ranked_items AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY total_orders DESC
        ) AS item_rank
    FROM item_counts
)

SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM ranked_items
WHERE item_rank <= 3;


--Q9.Are customer who are repeat buyers (more than 5 previous purchase) also likely to subscribe?--
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers,
    CAST(
        ROUND(
            COUNT(customer_id) * 100.0 
            / SUM(COUNT(customer_id)) OVER (), 
            2
        ) AS DECIMAL(5,2)
    ) AS percentage
FROM Customer_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group?--
SELECT age_group,
SUM(purchased_amount) as total_revenue
from customer_behavior
group by age_group
order by total_revenue DESC;

